### PR TITLE
Fix class name to FastAPI in app.py

### PR DESCRIPTION
**Pull request by tli-gini**
Fix class name to FastAPI in app.py

### CODE REVIEW

**Comment by tli-gini** [comment]
name: 童俐

**Review by cwpeng — APPROVED** [review]
OK.

**Comment by cwpeng** [comment]
You should merge pull request after review approval.

**Comment by tli-gini** [comment]
童俐
http://44.223.176.146:8000/api/attractions?page=1
http://44.223.176.146:8000/api/attractions?page=0&keyword=劍潭
http://44.223.176.146:8000/api/attractions?page=0&keyword=北
http://44.223.176.146:8000/api/attraction/10
http://44.223.176.146:8000/api/mrts

**Comment by cwpeng** [comment]
You should merge pull request after review approval. If you want to submit another task, you should create a new pull request for that. Read and take Part 0 guideline carefully.

**Pull request merged**
