### PR TITLE
update: small fix to create pull request

### PR DESCRIPTION
**Pull request by tli-gini**
童俐
http://54.175.58.48:8000/api/attractions?page=1
http://54.175.58.48:8000/api/attractions?page=0&keyword=劍潭
http://54.175.58.48:8000/api/attractions?page=0&keyword=北
http://54.175.58.48:8000/api/attraction/10
http://54.175.58.48:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your testing URLs. Tell me after they are ready.

**Comment by tli-gini** [comment]
童俐
week 1
http://34.228.25.52:8000/api/attractions?page=1
http://34.228.25.52:8000/api/attractions?page=0&keyword=劍潭
http://34.228.25.52:8000/api/attractions?page=0&keyword=北
http://34.228.25.52:8000/api/attraction/10
http://34.228.25.52:8000/api/mrts

week 2
http://34.228.25.52:8000/

**Comment by cwpeng** [comment]
You have closed your pull request so that I cannot review for you.

**Comment by tli-gini** [comment]
童俐
week 1
http://34.228.25.52:8000/api/attractions?page=1
http://34.228.25.52:8000/api/attractions?page=0&keyword=劍潭
http://34.228.25.52:8000/api/attractions?page=0&keyword=北
http://34.228.25.52:8000/api/attraction/10
http://34.228.25.52:8000/api/mrts

week 2
http://34.228.25.52:8000/

**Comment by cwpeng** [comment]
Cannot connect to your testing URLs.

**Comment by tli-gini** [comment]
童俐
week 1
http://34.228.25.52:8000/api/attractions?page=1
[http://34.228.25.52:8000/api/attractions?page=0&keyword=劍潭](http://34.228.25.52:8000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD)
[http://34.228.25.52:8000/api/attractions?page=0&keyword=北](http://34.228.25.52:8000/api/attractions?page=0&keyword=%E5%8C%97)
http://34.228.25.52:8000/api/attraction/10
http://34.228.25.52:8000/api/mrts

week 2
http://34.228.25.52:8000/

Please try again, thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your testing URLs.

**Comment by tli-gini** [comment]
童俐
week 1
http://34.228.25.52:8000/api/attractions?page=1
http://34.228.25.52:8000/api/attractions?page=0&keyword=劍潭
http://34.228.25.52:8000/api/attractions?page=0&keyword=北
http://34.228.25.52:8000/api/attraction/10
http://34.228.25.52:8000/api/mrts

week 2
http://34.228.25.52:8000/

I am sorry for the disconnection. I have launched the server using 'nohup' in the background. 
Please click the links again. Thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Week 1 is OK.

For week 2 task, when we click on MRT name, we should do keyword search and render results immediately.

**Comment by cwpeng** [comment]
Another issue for week 2 task, your layout width exceeds screen width in small devices.

**Comment by tli-gini** [comment]
week 2
http://34.228.25.52:8000/

I have pushed the latest version. Please check the link, thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot input keyword for searching.

**Comment by tli-gini** [comment]
童俐
http://34.228.25.52:8000/

I have tested and pushed the latest version.
Please check the link, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
